CREATE TABLE RELATIONSHIP(
  USER_FROM_ID NUMBER,
  CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY(USER_FROM_ID) REFERENCES USERS(ID),
  USER_TO_ID NUMBER,
  CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY(USER_TO_ID) REFERENCES USERS(ID),
  STATUS NVARCHAR2(50) NOT NULL
);

CREATE SEQUENCE RELATIONSHIP_ID_SEQ
  MINVALUE 1
  INCREMENT BY 1;


--mssql
-- CREATE TABLE [dbo].[RELATIONSHIP](
--   [USER_FROM_ID] [bigint] NOT NULL,
--   [USER_TO_ID] [bigint] NOT NULL,
--   [STATUS] [varchar](50) NOT NULL
-- )