CREATE TABLE USERS(
    USER_ID NUMBER,
        CONSTRAINT USERS_PK PRIMARY KEY(USER_ID),
    FIRST_NAME NVARCHAR2(50),
    LAST_NAME NVARCHAR2(50),
    PHONE NVARCHAR2(15),
    COUNTRY NVARCHAR2(50),
    CITY NVARCHAR2(50),
    AGE NUMBER,
    DATE_REGISTERED TIMESTAMP,
    DATE_LAST_ACTIVE TIMESTAMP,
    RELATIONSHIP_STATUS NVARCHAR2(20),
    RELIGION NVARCHAR2(20),
    SCHOOL NVARCHAR2(100),
    UNIVERSITY NVARCHAR2(100)
);

CREATE SEQUENCE USER_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;


--mysql
-- CREATE TABLE USERS(
--     USER_ID INT AUTO_INCREMENT,
--     FIRST_NAME VARCHAR(50),
--     LAST_NAME VARCHAR(50),
--     PHONE VARCHAR(15),
--     COUNTRY VARCHAR(50),
--     CITY VARCHAR(50),
--     AGE INT,
--     DATE_REGISTERED DATETIME,
--     DATE_LAST_ACTIVE DATETIME,
--     RELATIONSHIP_STATUS VARCHAR(20),
--     RELIGION VARCHAR(20),
--     SCHOOL VARCHAR(100),
--     UNIVERSITY VARCHAR(100),
--     PRIMARY KEY(USER_ID)
-- );