CREATE TABLE MESSAGE(
    MESSAGE_ID NUMBER,
        CONSTRAINT MESSAGE_PK PRIMARY KEY(MESSAGE_ID),
    TEXT BLOB,
    DATE_SENT TIMESTAMP,
    DATE_READ TIMESTAMP,
    USER_FROM_ID NUMBER,
        CONSTRAINT USER_FROM_FK FOREIGN KEY(USER_FROM_ID) REFERENCES USERS(USER_ID),
    USER_TO_ID NUMBER,
        CONSTRAINT USER_TO_FK FOREIGN KEY(USER_TO_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE MESSAGE_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;



--mysql
-- CREATE TABLE MESSAGE(
--     MESSAGE_ID INT AUTO_INCREMENT,
--     PRIMARY KEY(MESSAGE_ID),
--     TEXT BLOB,
--     DATE_SENT DATETIME,
--     DATE_READ DATETIME,
--     USER_FROM_ID INT,
--     FOREIGN KEY(USER_FROM_ID) REFERENCES USERS(USER_ID),
--     USER_TO_ID INT,
--     FOREIGN KEY(USER_TO_ID) REFERENCES USERS(USER_ID)
-- );