CREATE TABLE POST(
    ID NUMBER,
        CONSTRAINT POST_PK PRIMARY KEY(ID),
    MESSAGE NVARCHAR2(500),
    DATE_POSTED TIMESTAMP,
    USER_POSTED_ID NUMBER,
        CONSTRAINT USER_POSTED_FK FOREIGN KEY(USER_POSTED_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE POST_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;


--mssql
-- CREATE TABLE [dbo].[POST](
--     [ID] [bigint] IDENTITY(1,1) NOT NULL,
--     [MESSAGE] [varchar](500) NULL,
--     [DATE_POSTED] [timestamp] NOT NULL,
--     [USER_POSTED_ID] [bigint] NOT NULL,
-- CONSTRAINT [POST_PK] PRIMARY KEY CLUSTERED )

ALTER TABLE findme.dbo.POST ADD USER_PAGE_POSTED_ID BIGINT NULL
ALTER TABLE findme.dbo.POST ALTER COLUMN MESSAGE VARCHAR(200)