




--mssql
CREATE TABLE USERS_TAGGED(
  POST_ID BIGINT,
  CONSTRAINT POST_MEMBERS_POST_FK FOREIGN KEY(POST_ID) REFERENCES POST(ID),
  USER_ID BIGINT,
  CONSTRAINT POST_MEMBERS_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);