CREATE TABLE MESSAGE(
    MESSAGE_ID NUMBER,
        CONSTRAINT MESSAGE_PK PRIMARY KEY(MESSAGE_ID),
    TEXT BLOB,
    DATE_SENT TIMESTAMP,
    DATE_READ TIMESTAMP,
    USER_FROM_ID NUMBER,
        CONSTRAINT USER_FROM_FK FOREIGN KEY(USER_FROM_ID) REFERENCES USERS(USER_ID),
    USER_TO_ID NUMBER,
        CONSTRAINT USER_TO_FK FOREIGN KEY(USER_TO_ID) REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE MESSAGE_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;