CREATE TABLE USERS(
    USER_ID NUMBER,
        CONSTRAINT USERS_PK PRIMARY KEY(USER_ID),
    FIRST_NAME NVARCHAR2(50),
    LAST_NAME NVARCHAR2(50),
    PHONE NVARCHAR2(15),
    COUNTRY NVARCHAR2(50),
    CITY NVARCHAR2(50),
    AGE NUMBER,
    DATE_REGISTERED TIMESTAMP,
    DATE_LAST_ACTIVE TIMESTAMP,
    RELATIONSHIP_STATUS NVARCHAR2(20),
    RELIGION NVARCHAR2(20),
    SCHOOL NVARCHAR2(100),
    UNIVERSITY NVARCHAR2(100)
);

CREATE SEQUENCE USER_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;