CREATE TABLE POST(
    ID NUMBER,
        CONSTRAINT POST_PK PRIMARY KEY(ID),
    MESSAGE NVARCHAR2(200),
    DATE_POSTED TIMESTAMP,
    LOCATION NVARCHAR2(200),
    USER_POSTED_ID NUMBER,
        CONSTRAINT USER_POSTED_FK FOREIGN KEY(USER_POSTED_ID) REFERENCES USERS(ID),
    USER_PAGE_POSTED_ID NUMBER,
        CONSTRAINT USER_PAGE_POSTED_FK FOREIGN KEY(USER_PAGE_POSTED_ID) REFERENCES USERS(ID)
);

CREATE SEQUENCE POST_ID_SEQ
    MINVALUE 1
    INCREMENT BY 1;


-- mssql
-- CREATE TABLE [dbo].[POST](
--     [ID] [bigint] IDENTITY(1,1) NOT NULL,
-- CONSTRAINT [POST_PK] PRIMARY KEY CLUSTERED,
--     [MESSAGE] [varchar](200) NULL,
--     [DATE_POSTED] [timestamp] NOT NULL,
--     [LOCATION] [varchar](200),
--     [USER_POSTED_ID] [bigint] NOT NULL,
-- CONSTRAINT [USER_POSTED_FK] FOREIGN KEY([USER_POSTED_ID]) REFERENCES [dbo].[USERS] ([ID]),
--     [USER_PAGE_POSTED_ID] [bigint] NULL,
-- CONSTRAINT [USER_POSTED_FK] FOREIGN KEY([USER_POSTED_ID]) REFERENCES [dbo].[USERS] ([ID])
-- )
