CREATE TABLE COUNTRY (
  [ID] [bigint] IDENTITY(1,1) NOT NULL,
  [NAME] VARCHAR(50) NOT NULL
)
GO
ALTER TABLE findme.dbo.COUNTRY ADD CONSTRAINT COUNTRY_ID_pk PRIMARY KEY (ID)
GO

CREATE TABLE CITY (
[ID] [bigint] IDENTITY(1,1) NOT NULL,
[NAME] VARCHAR(50) NOT NULL,
[COUNTRY_ID] [bigint]
)
GO
ALTER TABLE findme.dbo.CITY ADD CONSTRAINT CITY_ID_pk PRIMARY KEY (ID)
GO
ALTER TABLE findme.dbo.CITY ADD CONSTRAINT CITY_COUNTRY_ID_fk FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
GO

CREATE TABLE USERS(
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [FIRST_NAME] [varchar](50) NOT NULL,
    [LAST_NAME] [varchar](50) NULL,
    [PHONE] [varchar](15) NOT NULL,
    [COUNTRY_ID] [BIGINT] NULL,
    [CITY] [varchar](50) NULL,
    [AGE] [int] NULL,
    [DATE_REGISTERED] [datetime] NULL,
    [DATE_LAST_ACTIVE] [datetime] NULL,
    [RELATIONSHIP_STATUS] [varchar](20) NULL,
    [RELIGION] [varchar](20) NULL,
    [SCHOOL] [varchar](100) NULL,
    [UNIVERSITY] [varchar](100) NULL,
    [PASSWORD] [varchar](50) NOT NULL,
    [EMAIL] [varchar](50) NOT NULL,
    [PHOTO] [image])
GO
ALTER TABLE findme.dbo.USERS ADD CONSTRAINT USER_ID_pk PRIMARY KEY (ID)
GO
ALTER TABLE findme.dbo.USERS ADD CONSTRAINT USERS_COUNTRY_ID_fk FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
GO

INSERT INTO USERS(FIRST_NAME, LAST_NAME, PHONE, PASSWORD, EMAIL)
VALUES ('Yevhen','Shepel','+380631111111','1111','admin@gm.com')
GO

CREATE TABLE [dbo].[POST](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [MESSAGE] [varchar](200) NULL,
    [DATE_POSTED] [timestamp] NOT NULL,
    [LOCATION] [varchar](200),
    [USER_POSTED_ID] [bigint] NOT NULL,
    [USER_PAGE_POSTED_ID] [bigint] NULL,
CONSTRAINT [USER_POSTED_FK] FOREIGN KEY([USER_POSTED_ID]) REFERENCES [dbo].[USERS] ([ID])
)
GO
ALTER TABLE findme.dbo.POST ADD CONSTRAINT POST_ID_pk PRIMARY KEY (ID)
GO
ALTER TABLE findme.dbo.POST ADD CONSTRAINT POST_USER_POSTED_FK FOREIGN KEY (USER_POSTED_ID) REFERENCES USERS (ID)
GO
ALTER TABLE findme.dbo.POST ADD CONSTRAINT POST_USER_PAGE_POSTED_FK FOREIGN KEY (USER_PAGE_POSTED_ID) REFERENCES USERS (ID)
GO

CREATE TABLE USERS_TAGGED(
  POST_ID BIGINT,
  CONSTRAINT POST_MEMBERS_POST_FK FOREIGN KEY(POST_ID) REFERENCES POST(ID),
  USER_ID BIGINT,
  CONSTRAINT POST_MEMBERS_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
)
GO
ALTER TABLE findme.dbo.USERS_TAGGED ADD CONSTRAINT USERS_TAGGED_USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
GO
ALTER TABLE findme.dbo.USERS_TAGGED ADD CONSTRAINT USERS_TAGGED_POST_FK FOREIGN KEY (POST_ID) REFERENCES POST (ID)
GO

CREATE TABLE RELATIONSHIP(
  USER_FROM_ID BIGINT,
  USER_TO_ID BIGINT,
  STATUS VARCHAR(50) NOT NULL,
  DATE_MODIFIED datetime
)
GO
ALTER TABLE findme.dbo.RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_USER_FROM_FK FOREIGN KEY (USER_FROM_ID) REFERENCES USERS(ID)
GO
ALTER TABLE findme.dbo.RELATIONSHIP ADD CONSTRAINT RELATIONSHIP_USER_TO_FK FOREIGN KEY (USER_TO_ID) REFERENCES USERS(ID)
GO

CREATE TABLE [dbo].[MESSAGE](
    [ID] [bigint] IDENTITY(1,1) NOT NULL,
    [TEXT] [varchar](max) NULL,
    [DATE_SENT] [datetime] NOT NULL,
    [DATE_READ] [datetime] NULL,
    [USER_FROM_ID] [bigint] NOT NULL,
    [USER_TO_ID] [bigint] NOT NULL,
    [DATE_EDITED] [datetime] NULL,
    [DATE_DELETED] [datetime] NULL

CONSTRAINT [MESSAGE_PK] PRIMARY KEY CLUSTERED)
GO
ALTER TABLE findme.dbo.MESSAGE ADD CONSTRAINT MESSAGE_ID_pk PRIMARY KEY (ID)
GO

